<?php

namespace Civix\ApiBundle\Controller\PublicApi;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class PostController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Civix\ApiBundle\Controller\PublicApi\PostController();
        return $instance;
    }
}
