<?php

namespace Civix\FrontBundle\Controller\Representative;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class SessionController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Civix\FrontBundle\Controller\Representative\SessionController();
        return $instance;
    }
}
