<?php

namespace Civix\ApiBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class AnnouncementController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Civix\ApiBundle\Controller\AnnouncementController();
        return $instance;
    }
}
