<?php

namespace Civix\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Civix\CoreBundle\Entity\Group;
use Civix\CoreBundle\Entity\GroupSection;

/**
 * GroupSectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupSectionRepository extends EntityRepository
{
    /**
     * @param Group $group
     * @return array
     */
    public function findByGroup(Group $group)
    {
        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('s, u')
            ->from('CivixCoreBundle:GroupSection', 's')
            ->leftJoin('s.users', 'u')
            ->where('s.group = :group')
            ->setParameter('group', $group)
            ->getQuery()
            ->getResult();
    }

    /**
     * @param Group $group
     * @return \Doctrine\ORM\Query
     */
    public function getUnassignedUsersQueryByGroup(GroupSection $section)
    {
        $ids = array(0);
        foreach ($section->getUsers() as $user) {
            $ids[] = $user->getId();
        }

        $qb = $this->getEntityManager()
            ->createQueryBuilder();

        return $qb->select('u')
            ->from('CivixCoreBundle:User', 'u')
            ->leftJoin('u.groups', 'ug')
            ->where($qb->expr()->notIn('u.id', $ids))
            ->andWhere('ug.group = :group')
            ->setParameter('group', $section->getGroup())
            ->orderBy('u.firstName')
            ->getQuery();
    }

    public function getDivisionsCount(Group $group)
    {
        return $this->getEntityManager()
            ->createQuery('SELECT count(gs) FROM CivixCoreBundle:GroupSection gs WHERE gs.group = :group')
            ->setParameter('group', $group)
            ->getSingleScalarResult()
        ;
    }
}
