<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140319162537 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE poll_questions_comments ADD petition_id INT DEFAULT NULL, ADD type VARCHAR(255) NOT NULL");
        $this->addSql("ALTER TABLE poll_questions_comments ADD CONSTRAINT FK_15824CD8AEC7D346 FOREIGN KEY (petition_id) REFERENCES micropetitions (id) ON DELETE CASCADE");
        $this->addSql("CREATE INDEX IDX_15824CD8AEC7D346 ON poll_questions_comments (petition_id)");
        $this->addSql("UPDATE poll_questions_comments SET type='poll' WHERE type IS NULL or type=''");
        $this->addSql("RENAME TABLE poll_questions_comments TO comments");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("RENAME TABLE comments TO poll_questions_comments");
        $this->addSql("ALTER TABLE poll_questions_comments DROP FOREIGN KEY FK_15824CD8AEC7D346");
        $this->addSql("DROP INDEX IDX_15824CD8AEC7D346 ON poll_questions_comments");
        $this->addSql("ALTER TABLE poll_questions_comments DROP petition_id, DROP type");
    }
}
