<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20131127092147 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE announcements ADD group_id INT DEFAULT NULL, ADD type VARCHAR(255) NOT NULL");
        $this->addSql("ALTER TABLE announcements ADD CONSTRAINT FK_F422A9DFE54D947 FOREIGN KEY (group_id) REFERENCES groups (id) ON DELETE CASCADE");
        $this->addSql("CREATE INDEX IDX_F422A9DFE54D947 ON announcements (group_id)");
        $this->addSql("UPDATE announcements SET type='representative' WHERE representative_id iS NOT NULL");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE announcements DROP FOREIGN KEY FK_F422A9DFE54D947");
        $this->addSql("DROP INDEX IDX_F422A9DFE54D947 ON announcements");
        $this->addSql("ALTER TABLE announcements DROP group_id, DROP type");
    }
}
