<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140117120929 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE representatives_storage ADD CONSTRAINT FK_AAB1F751A393D2FB FOREIGN KEY (state) REFERENCES states (code) ON DELETE SET NULL");
        $this->addSql("CREATE INDEX IDX_AAB1F751A393D2FB ON representatives_storage (state)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE representatives_storage DROP FOREIGN KEY FK_AAB1F751A393D2FB");
        $this->addSql("DROP INDEX IDX_AAB1F751A393D2FB ON representatives_storage");
    }
}
