<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140310165453 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("DROP TABLE bank_account");
        $this->addSql("DROP TABLE card");
        $this->addSql("ALTER TABLE balanced_payment ADD balanced_uri VARCHAR(255) DEFAULT NULL");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE bank_account (id INT AUTO_INCREMENT NOT NULL, owner_id INT DEFAULT NULL, name VARCHAR(100) NOT NULL, account_number VARCHAR(20) NOT NULL, routing_number VARCHAR(9) NOT NULL, type VARCHAR(255) NOT NULL, enabled TINYINT(1) NOT NULL, balanced_uri VARCHAR(255) NOT NULL, updated_at DATETIME DEFAULT NULL, created_at DATETIME NOT NULL, INDEX IDX_53A23E0A7E3C61F9 (owner_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE card (id INT AUTO_INCREMENT NOT NULL, owner_id INT DEFAULT NULL, number VARCHAR(16) NOT NULL, cvv VARCHAR(4) NOT NULL, exp_month INT NOT NULL, exp_year INT NOT NULL, enabled TINYINT(1) NOT NULL, balanced_uri VARCHAR(255) NOT NULL, updated_at DATETIME DEFAULT NULL, created_at DATETIME NOT NULL, INDEX IDX_161498D37E3C61F9 (owner_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("ALTER TABLE bank_account ADD CONSTRAINT FK_53A23E0A7E3C61F9 FOREIGN KEY (owner_id) REFERENCES customers (id)");
        $this->addSql("ALTER TABLE card ADD CONSTRAINT FK_161498D37E3C61F9 FOREIGN KEY (owner_id) REFERENCES customers (id)");
        $this->addSql("ALTER TABLE balanced_payment DROP balanced_uri");
    }
}
