<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20131126155127 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE groups_fields_values DROP FOREIGN KEY FK_7984E7FAA76ED395");
        $this->addSql("ALTER TABLE groups_fields_values ADD CONSTRAINT FK_7984E7FAA76ED395 FOREIGN KEY (user_id) REFERENCES user (id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE groups_fields_values DROP FOREIGN KEY FK_7984E7FAA76ED395");
        $this->addSql("ALTER TABLE groups_fields_values ADD CONSTRAINT FK_7984E7FAA76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE");
    }
}
