<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140303143216 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE balanced_payment (id INT AUTO_INCREMENT NOT NULL, from_user INT NOT NULL, to_user INT DEFAULT NULL, public_id VARCHAR(255) NOT NULL, amount DOUBLE PRECISION NOT NULL, currency VARCHAR(3) NOT NULL, reference VARCHAR(255) DEFAULT NULL, data LONGTEXT NOT NULL, state VARCHAR(10) NOT NULL, updated_at DATETIME DEFAULT NULL, created_at DATETIME NOT NULL, INDEX IDX_9E848ACFF8050BAA (from_user), INDEX IDX_9E848ACF6A7DC786 (to_user), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE card (id INT AUTO_INCREMENT NOT NULL, owner_id INT DEFAULT NULL, number VARCHAR(16) NOT NULL, cvv VARCHAR(4) NOT NULL, exp_month INT NOT NULL, exp_year INT NOT NULL, enabled TINYINT(1) NOT NULL, balanced_uri VARCHAR(255) NOT NULL, updated_at DATETIME DEFAULT NULL, created_at DATETIME NOT NULL, INDEX IDX_161498D37E3C61F9 (owner_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE bank_account (id INT AUTO_INCREMENT NOT NULL, owner_id INT DEFAULT NULL, name VARCHAR(100) NOT NULL, account_number VARCHAR(20) NOT NULL, routing_number VARCHAR(9) NOT NULL, type VARCHAR(255) NOT NULL, enabled TINYINT(1) NOT NULL, balanced_uri VARCHAR(255) NOT NULL, updated_at DATETIME DEFAULT NULL, created_at DATETIME NOT NULL, INDEX IDX_53A23E0A7E3C61F9 (owner_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE customers (id INT AUTO_INCREMENT NOT NULL, representative_id INT DEFAULT NULL, group_id INT DEFAULT NULL, balanced_uri VARCHAR(255) DEFAULT NULL, type VARCHAR(255) NOT NULL, INDEX IDX_62534E21FC3FF006 (representative_id), INDEX IDX_62534E21FE54D947 (group_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("ALTER TABLE balanced_payment ADD CONSTRAINT FK_9E848ACFF8050BAA FOREIGN KEY (from_user) REFERENCES customers (id)");
        $this->addSql("ALTER TABLE balanced_payment ADD CONSTRAINT FK_9E848ACF6A7DC786 FOREIGN KEY (to_user) REFERENCES customers (id)");
        $this->addSql("ALTER TABLE card ADD CONSTRAINT FK_161498D37E3C61F9 FOREIGN KEY (owner_id) REFERENCES customers (id)");
        $this->addSql("ALTER TABLE bank_account ADD CONSTRAINT FK_53A23E0A7E3C61F9 FOREIGN KEY (owner_id) REFERENCES customers (id)");
        $this->addSql("ALTER TABLE customers ADD CONSTRAINT FK_62534E21FC3FF006 FOREIGN KEY (representative_id) REFERENCES representatives (id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE customers ADD CONSTRAINT FK_62534E21FE54D947 FOREIGN KEY (group_id) REFERENCES groups (id) ON DELETE CASCADE");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE balanced_payment DROP FOREIGN KEY FK_9E848ACFF8050BAA");
        $this->addSql("ALTER TABLE balanced_payment DROP FOREIGN KEY FK_9E848ACF6A7DC786");
        $this->addSql("ALTER TABLE card DROP FOREIGN KEY FK_161498D37E3C61F9");
        $this->addSql("ALTER TABLE bank_account DROP FOREIGN KEY FK_53A23E0A7E3C61F9");
        $this->addSql("DROP TABLE balanced_payment");
        $this->addSql("DROP TABLE card");
        $this->addSql("DROP TABLE bank_account");
        $this->addSql("DROP TABLE customers");
    }
}
