<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20131213104437 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE ActivityCondition (id INT AUTO_INCREMENT NOT NULL, activity_id INT DEFAULT NULL, group_id INT DEFAULT NULL, district_id INT DEFAULT NULL, is_superuser TINYINT(1) DEFAULT NULL, user_id INT DEFAULT NULL, INDEX IDX_9F4ECD7481C06096 (activity_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("ALTER TABLE ActivityCondition ADD CONSTRAINT FK_9F4ECD7481C06096 FOREIGN KEY (activity_id) REFERENCES activities (id) ON DELETE CASCADE");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("DROP TABLE ActivityCondition");
    }
}
