<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

use Symfony\Bundle\FrameworkBundle\Console\Application;
use Symfony\Component\Console\Input\ArgvInput;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140127190447 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $kernel = new \AppKernel('prod', false);
        $application = new Application($kernel);
        $application->setAutoExit(false);
        $application->run(new ArgvInput(array('', 'sns-migrate')));
        $kernel->shutdown();
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
    }
}
