<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140113110902 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE users_groups DROP PRIMARY KEY");
        $this->addSql("ALTER TABLE users_groups ADD id INT AUTO_INCREMENT PRIMARY KEY NOT NULL, CHANGE user_id user_id INT DEFAULT NULL, CHANGE group_id group_id INT DEFAULT NULL");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE users_groups DROP PRIMARY KEY");
        $this->addSql("ALTER TABLE users_groups DROP id, CHANGE user_id user_id INT NOT NULL, CHANGE group_id group_id INT NOT NULL");
        $this->addSql("ALTER TABLE users_groups ADD PRIMARY KEY (user_id, group_id)");
    }
}
