<?php

namespace Civix\FrontBundle\Controller\Superuser;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class PostController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Civix\FrontBundle\Controller\Superuser\PostController();
        return $instance;
    }
}
