<?php

namespace Civix\FrontBundle\Controller\Group;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class FieldsController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Civix\FrontBundle\Controller\Group\FieldsController();
        return $instance;
    }
}
