<?php

namespace Civix\ApiBundle\Controller\Leader;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class MicroPetitionController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Civix\ApiBundle\Controller\Leader\MicroPetitionController();
        return $instance;
    }
}
