<?php

namespace Civix\FrontBundle\Controller\Group;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class SectionsController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Civix\FrontBundle\Controller\Group\SectionsController();
        return $instance;
    }
}
