<?php

namespace Nelmio\ApiDocBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class ApiDocController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Nelmio\ApiDocBundle\Controller\ApiDocController();
        return $instance;
    }
}
