<?php

namespace Proxies\__CG__\Civix\CoreBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class HashTag extends \Civix\CoreBundle\Entity\HashTag implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setName($name)
    {
        $this->__load();
        return parent::setName($name);
    }

    public function getName()
    {
        $this->__load();
        return parent::getName();
    }

    public function addPetition(\Civix\CoreBundle\Entity\Micropetitions\Petition $petitions)
    {
        $this->__load();
        return parent::addPetition($petitions);
    }

    public function removePetition(\Civix\CoreBundle\Entity\Micropetitions\Petition $petitions)
    {
        $this->__load();
        return parent::removePetition($petitions);
    }

    public function getPetitions()
    {
        $this->__load();
        return parent::getPetitions();
    }

    public function addQuestion(\Civix\CoreBundle\Entity\Poll\Question $question)
    {
        $this->__load();
        return parent::addQuestion($question);
    }

    public function removeQuestion(\Civix\CoreBundle\Entity\Poll\Question $question)
    {
        $this->__load();
        return parent::removeQuestion($question);
    }

    public function getQuestions()
    {
        $this->__load();
        return parent::getQuestions();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'name', 'petitions', 'questions');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}