<?php

namespace Proxies\__CG__\Civix\CoreBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class SocialActivity extends \Civix\CoreBundle\Entity\SocialActivity implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setId($id)
    {
        $this->__load();
        return parent::setId($id);
    }

    public function getRecipient()
    {
        $this->__load();
        return parent::getRecipient();
    }

    public function setRecipient(\Civix\CoreBundle\Entity\User $recipient)
    {
        $this->__load();
        return parent::setRecipient($recipient);
    }

    public function getGroup()
    {
        $this->__load();
        return parent::getGroup();
    }

    public function setGroup(\Civix\CoreBundle\Entity\Group $group)
    {
        $this->__load();
        return parent::setGroup($group);
    }

    public function getType()
    {
        $this->__load();
        return parent::getType();
    }

    public function setType($type)
    {
        $this->__load();
        return parent::setType($type);
    }

    public function getCreatedAt()
    {
        $this->__load();
        return parent::getCreatedAt();
    }

    public function setCreatedAt(\DateTime $createdAt)
    {
        $this->__load();
        return parent::setCreatedAt($createdAt);
    }

    public function getTarget()
    {
        $this->__load();
        return parent::getTarget();
    }

    public function setTarget($target)
    {
        $this->__load();
        return parent::setTarget($target);
    }

    public function isIgnore()
    {
        $this->__load();
        return parent::isIgnore();
    }

    public function setIgnore($ignore)
    {
        $this->__load();
        return parent::setIgnore($ignore);
    }

    public function getFollowing()
    {
        $this->__load();
        return parent::getFollowing();
    }

    public function setFollowing(\Civix\CoreBundle\Entity\User $following)
    {
        $this->__load();
        return parent::setFollowing($following);
    }

    public function getActivityTab()
    {
        $this->__load();
        return parent::getActivityTab();
    }

    public function getHTMLMessage()
    {
        $this->__load();
        return parent::getHTMLMessage();
    }

    public function getTextMessage()
    {
        $this->__load();
        return parent::getTextMessage();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'type', 'createdAt', 'target', 'ignore', 'group', 'recipient', 'following');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}