<?php

namespace Proxies\__CG__\Civix\CoreBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class User extends \Civix\CoreBundle\Entity\User implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function addInvite(\Civix\CoreBundle\Entity\Group $group)
    {
        $this->__load();
        return parent::addInvite($group);
    }

    public function removeInvite(\Civix\CoreBundle\Entity\Group $group)
    {
        $this->__load();
        return parent::removeInvite($group);
    }

    public function getInvites()
    {
        $this->__load();
        return parent::getInvites();
    }

    public function addFollowing(\Civix\CoreBundle\Entity\UserFollow $following)
    {
        $this->__load();
        return parent::addFollowing($following);
    }

    public function removeFollowing(\Civix\CoreBundle\Entity\UserFollow $following)
    {
        $this->__load();
        return parent::removeFollowing($following);
    }

    public function getFollowing()
    {
        $this->__load();
        return parent::getFollowing();
    }

    public function addFollower(\Civix\CoreBundle\Entity\UserFollow $follower)
    {
        $this->__load();
        return parent::addFollower($follower);
    }

    public function removeFollower(\Civix\CoreBundle\Entity\UserFollow $follower)
    {
        $this->__load();
        return parent::removeFollower($follower);
    }

    public function getFollowers()
    {
        $this->__load();
        return parent::getFollowers();
    }

    public function setUsername($username)
    {
        $this->__load();
        return parent::setUsername($username);
    }

    public function getUsername()
    {
        $this->__load();
        return parent::getUsername();
    }

    public function setPassword($password)
    {
        $this->__load();
        return parent::setPassword($password);
    }

    public function getPassword()
    {
        $this->__load();
        return parent::getPassword();
    }

    public function setSalt($salt)
    {
        $this->__load();
        return parent::setSalt($salt);
    }

    public function getSalt()
    {
        $this->__load();
        return parent::getSalt();
    }

    public function setFirstName($firstName)
    {
        $this->__load();
        return parent::setFirstName($firstName);
    }

    public function getFirstName()
    {
        $this->__load();
        return parent::getFirstName();
    }

    public function setLastName($lastName)
    {
        $this->__load();
        return parent::setLastName($lastName);
    }

    public function getLastName()
    {
        $this->__load();
        return parent::getLastName();
    }

    public function setEmail($email)
    {
        $this->__load();
        return parent::setEmail($email);
    }

    public function getEmail()
    {
        $this->__load();
        return parent::getEmail();
    }

    public function setZip($zip)
    {
        $this->__load();
        return parent::setZip($zip);
    }

    public function getZip()
    {
        $this->__load();
        return parent::getZip();
    }

    public function setAvatar($avatar)
    {
        $this->__load();
        return parent::setAvatar($avatar);
    }

    public function getAvatar()
    {
        $this->__load();
        return parent::getAvatar();
    }

    public function getDefaultAvatar()
    {
        $this->__load();
        return parent::getDefaultAvatar();
    }

    public function getAvatarWithPath($privacy = false)
    {
        $this->__load();
        return parent::getAvatarWithPath($privacy);
    }

    public function setAvatarPath($path)
    {
        $this->__load();
        return parent::setAvatarPath($path);
    }

    public function setBirth($birth)
    {
        $this->__load();
        return parent::setBirth($birth);
    }

    public function getBirth()
    {
        $this->__load();
        return parent::getBirth();
    }

    public function setAddress1($address1)
    {
        $this->__load();
        return parent::setAddress1($address1);
    }

    public function getAddress1()
    {
        $this->__load();
        return parent::getAddress1();
    }

    public function setAddress2($address2)
    {
        $this->__load();
        return parent::setAddress2($address2);
    }

    public function getAddress2()
    {
        $this->__load();
        return parent::getAddress2();
    }

    public function setCity($city)
    {
        $this->__load();
        return parent::setCity($city);
    }

    public function getCity()
    {
        $this->__load();
        return parent::getCity();
    }

    public function setState($state)
    {
        $this->__load();
        return parent::setState($state);
    }

    public function getState()
    {
        $this->__load();
        return parent::getState();
    }

    public function getCountry()
    {
        $this->__load();
        return parent::getCountry();
    }

    public function setCountry($country)
    {
        $this->__load();
        return parent::setCountry($country);
    }

    public function setPhone($phone)
    {
        $this->__load();
        return parent::setPhone($phone);
    }

    public function getPhone()
    {
        $this->__load();
        return parent::getPhone();
    }

    public function setFacebookLink($facebookLink)
    {
        $this->__load();
        return parent::setFacebookLink($facebookLink);
    }

    public function getFacebookLink()
    {
        $this->__load();
        return parent::getFacebookLink();
    }

    public function setTwitterLink($twitterLink)
    {
        $this->__load();
        return parent::setTwitterLink($twitterLink);
    }

    public function getTwitterLink()
    {
        $this->__load();
        return parent::getTwitterLink();
    }

    public function setRace($race)
    {
        $this->__load();
        return parent::setRace($race);
    }

    public function getRace()
    {
        $this->__load();
        return parent::getRace();
    }

    public function setSex($sex)
    {
        $this->__load();
        return parent::setSex($sex);
    }

    public function getSex()
    {
        $this->__load();
        return parent::getSex();
    }

    public function setMaritalStatus($maritalStatus)
    {
        $this->__load();
        return parent::setMaritalStatus($maritalStatus);
    }

    public function getMaritalStatus()
    {
        $this->__load();
        return parent::getMaritalStatus();
    }

    public function setReligion($religion)
    {
        $this->__load();
        return parent::setReligion($religion);
    }

    public function getReligion()
    {
        $this->__load();
        return parent::getReligion();
    }

    public function setEmploymentStatus($employmentStatus)
    {
        $this->__load();
        return parent::setEmploymentStatus($employmentStatus);
    }

    public function getEmploymentStatus()
    {
        $this->__load();
        return parent::getEmploymentStatus();
    }

    public function setIncomeLevel($incomeLevel)
    {
        $this->__load();
        return parent::setIncomeLevel($incomeLevel);
    }

    public function getIncomeLevel()
    {
        $this->__load();
        return parent::getIncomeLevel();
    }

    public function setEducationLevel($educationLevel)
    {
        $this->__load();
        return parent::setEducationLevel($educationLevel);
    }

    public function getEducationLevel()
    {
        $this->__load();
        return parent::getEducationLevel();
    }

    public function setToken($token)
    {
        $this->__load();
        return parent::setToken($token);
    }

    public function getToken()
    {
        $this->__load();
        return parent::getToken();
    }

    public function getRoles()
    {
        $this->__load();
        return parent::getRoles();
    }

    public function eraseCredentials()
    {
        $this->__load();
        return parent::eraseCredentials();
    }

    public function generateToken()
    {
        $this->__load();
        return parent::generateToken();
    }

    public function getDistrictsIds()
    {
        $this->__load();
        return parent::getDistrictsIds();
    }

    public function setUpdateProfileAt($updateDate)
    {
        $this->__load();
        return parent::setUpdateProfileAt($updateDate);
    }

    public function getUpdateProfileAt()
    {
        $this->__load();
        return parent::getUpdateProfileAt();
    }

    public function getIosDevice()
    {
        $this->__load();
        return parent::getIosDevice();
    }

    public function setIosToken($token)
    {
        $this->__load();
        return parent::setIosToken($token);
    }

    public function getAndroidDevice()
    {
        $this->__load();
        return parent::getAndroidDevice();
    }

    public function setAndroidToken($token)
    {
        $this->__load();
        return parent::setAndroidToken($token);
    }

    public function getUserGroups()
    {
        $this->__load();
        return parent::getUserGroups();
    }

    public function getGroups()
    {
        $this->__load();
        return parent::getGroups();
    }

    public function removeGroup(\Civix\CoreBundle\Entity\UserGroup $group)
    {
        $this->__load();
        return parent::removeGroup($group);
    }

    public function getLineAddress()
    {
        $this->__load();
        return parent::getLineAddress();
    }

    public function getGroupsIds()
    {
        $this->__load();
        return parent::getGroupsIds();
    }

    public function getFollowingIds()
    {
        $this->__load();
        return parent::getFollowingIds();
    }

    public function serialize()
    {
        $this->__load();
        return parent::serialize();
    }

    public function unserialize($serialized)
    {
        $this->__load();
        return parent::unserialize($serialized);
    }

    public function getOfficialName()
    {
        $this->__load();
        return parent::getOfficialName();
    }

    public function addDistrict(\Civix\CoreBundle\Entity\District $district)
    {
        $this->__load();
        return parent::addDistrict($district);
    }

    public function removeDistrict(\Civix\CoreBundle\Entity\District $districts)
    {
        $this->__load();
        return parent::removeDistrict($districts);
    }

    public function getDistricts()
    {
        $this->__load();
        return parent::getDistricts();
    }

    public function addGroupSection(\Civix\CoreBundle\Entity\GroupSection $section)
    {
        $this->__load();
        return parent::addGroupSection($section);
    }

    public function removeGroupSection(\Civix\CoreBundle\Entity\GroupSection $section)
    {
        $this->__load();
        return parent::removeGroupSection($section);
    }

    public function getGroupSections()
    {
        $this->__load();
        return parent::getGroupSections();
    }

    public function getGroupSectionsIds()
    {
        $this->__load();
        return parent::getGroupSectionsIds();
    }

    public function setDoNotDisturb($doNotDisturb)
    {
        $this->__load();
        return parent::setDoNotDisturb($doNotDisturb);
    }

    public function getDoNotDisturb()
    {
        $this->__load();
        return parent::getDoNotDisturb();
    }

    public function setIsNotifQuestions($isNotifQuestions)
    {
        $this->__load();
        return parent::setIsNotifQuestions($isNotifQuestions);
    }

    public function getIsNotifQuestions()
    {
        $this->__load();
        return parent::getIsNotifQuestions();
    }

    public function setIsNotifDiscussions($isNotifDiscussions)
    {
        $this->__load();
        return parent::setIsNotifDiscussions($isNotifDiscussions);
    }

    public function getIsNotifDiscussions()
    {
        $this->__load();
        return parent::getIsNotifDiscussions();
    }

    public function setIsNotifMessages($isNotifMessages)
    {
        $this->__load();
        return parent::setIsNotifMessages($isNotifMessages);
    }

    public function getIsNotifMessages()
    {
        $this->__load();
        return parent::getIsNotifMessages();
    }

    public function setIsNotifMicroFollowing($isNotifMicroFollowing)
    {
        $this->__load();
        return parent::setIsNotifMicroFollowing($isNotifMicroFollowing);
    }

    public function getIsNotifMicroFollowing()
    {
        $this->__load();
        return parent::getIsNotifMicroFollowing();
    }

    public function setIsNotifMicroGroup($isNotifMicroGroup)
    {
        $this->__load();
        return parent::setIsNotifMicroGroup($isNotifMicroGroup);
    }

    public function getIsNotifMicroGroup()
    {
        $this->__load();
        return parent::getIsNotifMicroGroup();
    }

    public function addGroup(\Civix\CoreBundle\Entity\UserGroup $usergroup)
    {
        $this->__load();
        return parent::addGroup($usergroup);
    }

    public function setIsNotifScheduled($isNotifSchedule)
    {
        $this->__load();
        return parent::setIsNotifScheduled($isNotifSchedule);
    }

    public function getIsNotifScheduled()
    {
        $this->__load();
        return parent::getIsNotifScheduled();
    }

    public function setScheduledFrom($scheduleFrom)
    {
        $this->__load();
        return parent::setScheduledFrom($scheduleFrom);
    }

    public function getScheduledFrom()
    {
        $this->__load();
        return parent::getScheduledFrom();
    }

    public function setScheduledTo($scheduleTo)
    {
        $this->__load();
        return parent::setScheduledTo($scheduleTo);
    }

    public function getScheduledTo()
    {
        $this->__load();
        return parent::getScheduledTo();
    }

    public function setOrientation($orientation)
    {
        $this->__load();
        return parent::setOrientation($orientation);
    }

    public function getOrientation()
    {
        $this->__load();
        return parent::getOrientation();
    }

    public function setParty($party)
    {
        $this->__load();
        return parent::setParty($party);
    }

    public function getParty()
    {
        $this->__load();
        return parent::getParty();
    }

    public function setPhilosophy($philosophy)
    {
        $this->__load();
        return parent::setPhilosophy($philosophy);
    }

    public function getPhilosophy()
    {
        $this->__load();
        return parent::getPhilosophy();
    }

    public function setDonor($donor)
    {
        $this->__load();
        return parent::setDonor($donor);
    }

    public function getDonor()
    {
        $this->__load();
        return parent::getDonor();
    }

    public function setRegistration($registration)
    {
        $this->__load();
        return parent::setRegistration($registration);
    }

    public function getRegistration()
    {
        $this->__load();
        return parent::getRegistration();
    }

    public function getSlogan()
    {
        $this->__load();
        return parent::getSlogan();
    }

    public function setSlogan($slogan)
    {
        $this->__load();
        return parent::setSlogan($slogan);
    }

    public function getBio()
    {
        $this->__load();
        return parent::getBio();
    }

    public function setBio($bio)
    {
        $this->__load();
        return parent::setBio($bio);
    }

    public function getInterests()
    {
        $this->__load();
        return parent::getInterests();
    }

    public function setInterests($interests)
    {
        $this->__load();
        return parent::setInterests($interests);
    }

    public function setFacebookId($facebookId)
    {
        $this->__load();
        return parent::setFacebookId($facebookId);
    }

    public function getFacebookId()
    {
        $this->__load();
        return parent::getFacebookId();
    }

    public function setFacebookToken($facebookToken)
    {
        $this->__load();
        return parent::setFacebookToken($facebookToken);
    }

    public function getFacebookToken()
    {
        $this->__load();
        return parent::getFacebookToken();
    }

    public function setIsRegistrationComplete($isRegistrationComplete)
    {
        $this->__load();
        return parent::setIsRegistrationComplete($isRegistrationComplete);
    }

    public function getIsRegistrationComplete()
    {
        $this->__load();
        return parent::getIsRegistrationComplete();
    }

    public function getPlainPassword()
    {
        $this->__load();
        return parent::getPlainPassword();
    }

    public function setPlainPassword($plainPassword)
    {
        $this->__load();
        return parent::setPlainPassword($plainPassword);
    }

    public function setAvatarFileName($avatarFileName)
    {
        $this->__load();
        return parent::setAvatarFileName($avatarFileName);
    }

    public function getAvatarFileName()
    {
        $this->__load();
        return parent::getAvatarFileName();
    }

    public function setResetPasswordAt($resetPasswordAt)
    {
        $this->__load();
        return parent::setResetPasswordAt($resetPasswordAt);
    }

    public function getResetPasswordAt()
    {
        $this->__load();
        return parent::getResetPasswordAt();
    }

    public function setResetPasswordToken($resetPasswordToken)
    {
        $this->__load();
        return parent::setResetPasswordToken($resetPasswordToken);
    }

    public function getResetPasswordToken()
    {
        $this->__load();
        return parent::getResetPasswordToken();
    }

    public function getType()
    {
        $this->__load();
        return parent::getType();
    }

    public function getFullName()
    {
        $this->__load();
        return parent::getFullName();
    }

    public function getAddressArray()
    {
        $this->__load();
        return parent::getAddressArray();
    }

    public function getAddressQuery()
    {
        $this->__load();
        return parent::getAddressQuery();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'username', 'password', 'salt', 'firstName', 'lastName', 'email', 'zip', 'avatarFileName', 'birth', 'address1', 'address2', 'city', 'state', 'country', 'phone', 'facebookLink', 'twitterLink', 'race', 'sex', 'orientation', 'maritalStatus', 'religion', 'employmentStatus', 'incomeLevel', 'educationLevel', 'party', 'philosophy', 'donor', 'bio', 'slogan', 'interests', 'registration', 'token', 'facebookId', 'facebookToken', 'updateProfileAt', 'iosDevice', 'androidDevice', 'doNotDisturb', 'isNotifQuestions', 'isNotifDiscussions', 'isNotifMessages', 'isNotifMicroFollowing', 'isNotifMicroGroup', 'isNotifScheduled', 'scheduledFrom', 'scheduledTo', 'isRegistrationComplete', 'resetPasswordAt', 'resetPasswordToken', 'groups', 'invites', 'following', 'followers', 'districts', 'groupSections');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}