<?php

namespace Proxies\__CG__\Civix\CoreBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class UserGroup extends \Civix\CoreBundle\Entity\UserGroup implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setStatus($status)
    {
        $this->__load();
        return parent::setStatus($status);
    }

    public function getStatus()
    {
        $this->__load();
        return parent::getStatus();
    }

    public function setUser(\Civix\CoreBundle\Entity\User $user)
    {
        $this->__load();
        return parent::setUser($user);
    }

    public function getUser()
    {
        $this->__load();
        return parent::getUser();
    }

    public function setGroup(\Civix\CoreBundle\Entity\Group $group)
    {
        $this->__load();
        return parent::setGroup($group);
    }

    public function getGroup()
    {
        $this->__load();
        return parent::getGroup();
    }

    public function getGroupId()
    {
        $this->__load();
        return parent::getGroupId();
    }

    public function setGroupId($group_id)
    {
        $this->__load();
        return parent::setGroupId($group_id);
    }

    public function setCreatedAt($createdAt)
    {
        $this->__load();
        return parent::setCreatedAt($createdAt);
    }

    public function getCreatedAt()
    {
        $this->__load();
        return parent::getCreatedAt();
    }

    public function setPermissionsName($permissionsName)
    {
        $this->__load();
        return parent::setPermissionsName($permissionsName);
    }

    public function getPermissionsName()
    {
        $this->__load();
        return parent::getPermissionsName();
    }

    public function setPermissionsContacts($permissionsContacts)
    {
        $this->__load();
        return parent::setPermissionsContacts($permissionsContacts);
    }

    public function getPermissionsContacts()
    {
        $this->__load();
        return parent::getPermissionsContacts();
    }

    public function setPermissionsResponses($permissionsResponses)
    {
        $this->__load();
        return parent::setPermissionsResponses($permissionsResponses);
    }

    public function getPermissionsResponses()
    {
        $this->__load();
        return parent::getPermissionsResponses();
    }

    public function getPermissionsAddress()
    {
        $this->__load();
        return parent::getPermissionsAddress();
    }

    public function setPermissionsAddress($permissionsAddress)
    {
        $this->__load();
        return parent::setPermissionsAddress($permissionsAddress);
    }

    public function getPermissionsEmail()
    {
        $this->__load();
        return parent::getPermissionsEmail();
    }

    public function setPermissionsEmail($permissionsEmail)
    {
        $this->__load();
        return parent::setPermissionsEmail($permissionsEmail);
    }

    public function getPermissionsPhone()
    {
        $this->__load();
        return parent::getPermissionsPhone();
    }

    public function setPermissionsPhone($permissionsPhone)
    {
        $this->__load();
        return parent::setPermissionsPhone($permissionsPhone);
    }

    public function setPermissionsApprovedAt($permissionsApprovedAt)
    {
        $this->__load();
        return parent::setPermissionsApprovedAt($permissionsApprovedAt);
    }

    public function getPermissionsApprovedAt()
    {
        $this->__load();
        return parent::getPermissionsApprovedAt();
    }

    public function setPermissionsByGroup(\Civix\CoreBundle\Entity\Group $group)
    {
        $this->__load();
        return parent::setPermissionsByGroup($group);
    }

    public function getUserDataRow()
    {
        $this->__load();
        return parent::getUserDataRow();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'group_id', 'createdAt', 'status', 'permissionsName', 'permissionsContacts', 'permissionsAddress', 'permissionsEmail', 'permissionsPhone', 'permissionsResponses', 'permissionsApprovedAt', 'user', 'group');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}