<?php

namespace Proxies\__CG__\Civix\CoreBundle\Entity\Poll;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Answer extends \Civix\CoreBundle\Entity\Poll\Answer implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setPrivacy($privacy)
    {
        $this->__load();
        return parent::setPrivacy($privacy);
    }

    public function getPrivacy()
    {
        $this->__load();
        return parent::getPrivacy();
    }

    public function getUserInfo()
    {
        $this->__load();
        return parent::getUserInfo();
    }

    public function setUser(\Civix\CoreBundle\Entity\User $user = NULL)
    {
        $this->__load();
        return parent::setUser($user);
    }

    public function getUser()
    {
        $this->__load();
        return parent::getUser();
    }

    public function setComment($comment)
    {
        $this->__load();
        return parent::setComment($comment);
    }

    public function getComment()
    {
        $this->__load();
        return parent::getComment();
    }

    public function setQuestion(\Civix\CoreBundle\Entity\Poll\Question $question = NULL)
    {
        $this->__load();
        return parent::setQuestion($question);
    }

    public function getQuestion()
    {
        $this->__load();
        return parent::getQuestion();
    }

    public function setOption(\Civix\CoreBundle\Entity\Poll\Option $option = NULL)
    {
        $this->__load();
        return parent::setOption($option);
    }

    public function getOption()
    {
        $this->__load();
        return parent::getOption();
    }

    public function setPaymentAmount($payment_amount)
    {
        $this->__load();
        return parent::setPaymentAmount($payment_amount);
    }

    public function getPaymentAmount()
    {
        $this->__load();
        return parent::getPaymentAmount();
    }

    public function getCurrentPaymentAmount()
    {
        $this->__load();
        return parent::getCurrentPaymentAmount();
    }

    public function setCurrentTimeAsCreatedAt()
    {
        $this->__load();
        return parent::setCurrentTimeAsCreatedAt();
    }

    public function setCreatedAt($createdAt)
    {
        $this->__load();
        return parent::setCreatedAt($createdAt);
    }

    public function getCreatedAt()
    {
        $this->__load();
        return parent::getCreatedAt();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'optionId', 'comment', 'payment_amount', 'privacy', 'createdAt', 'user', 'option', 'question');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}