<?php

namespace Proxies\__CG__\Civix\CoreBundle\Entity\Group;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class GroupField extends \Civix\CoreBundle\Entity\Group\GroupField implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setFieldName($fieldName)
    {
        $this->__load();
        return parent::setFieldName($fieldName);
    }

    public function getFieldName()
    {
        $this->__load();
        return parent::getFieldName();
    }

    public function setGroup(\Civix\CoreBundle\Entity\Group $group = NULL)
    {
        $this->__load();
        return parent::setGroup($group);
    }

    public function getGroup()
    {
        $this->__load();
        return parent::getGroup();
    }

    public function addValue(\Civix\CoreBundle\Entity\Group\FieldValue $values)
    {
        $this->__load();
        return parent::addValue($values);
    }

    public function removeValue(\Civix\CoreBundle\Entity\Group\FieldValue $values)
    {
        $this->__load();
        return parent::removeValue($values);
    }

    public function getValues()
    {
        $this->__load();
        return parent::getValues();
    }

    public function getUserValue(\Civix\CoreBundle\Entity\User $user)
    {
        $this->__load();
        return parent::getUserValue($user);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'fieldName', 'group', 'values');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}