<?php

namespace Proxies\__CG__\Civix\CoreBundle\Entity\Customer\Order;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class PaymentRequestOrder extends \Civix\CoreBundle\Entity\Customer\Order\PaymentRequestOrder implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function setPaymentRequest($paymentRequest)
    {
        $this->__load();
        return parent::setPaymentRequest($paymentRequest);
    }

    public function getPaymentRequest()
    {
        $this->__load();
        return parent::getPaymentRequest();
    }

    public function setBalancedUri($balancedUri)
    {
        $this->__load();
        return parent::setBalancedUri($balancedUri);
    }

    public function getBalancedUri()
    {
        $this->__load();
        return parent::getBalancedUri();
    }

    public function setCreatedAt($createdAt)
    {
        $this->__load();
        return parent::setCreatedAt($createdAt);
    }

    public function getCreatedAt()
    {
        $this->__load();
        return parent::getCreatedAt();
    }

    public function setId($id)
    {
        $this->__load();
        return parent::setId($id);
    }

    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setUpdatedAt($updatedAt)
    {
        $this->__load();
        return parent::setUpdatedAt($updatedAt);
    }

    public function getUpdatedAt()
    {
        $this->__load();
        return parent::getUpdatedAt();
    }

    public function beforePersist()
    {
        $this->__load();
        return parent::beforePersist();
    }

    public function beforeUpdate()
    {
        $this->__load();
        return parent::beforeUpdate();
    }

    public function setPublicId($publicId)
    {
        $this->__load();
        return parent::setPublicId($publicId);
    }

    public function getPublicId()
    {
        $this->__load();
        return parent::getPublicId();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'balancedUri', 'updatedAt', 'publicId', 'createdAt', 'paymentRequest');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}