<?php

namespace Proxies\__CG__\Civix\CoreBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Group extends \Civix\CoreBundle\Entity\Group implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function init()
    {
        $this->__load();
        return parent::init();
    }

    public function addInvite(\Civix\CoreBundle\Entity\User $user)
    {
        $this->__load();
        return parent::addInvite($user);
    }

    public function removeInvite(\Civix\CoreBundle\Entity\User $user)
    {
        $this->__load();
        return parent::removeInvite($user);
    }

    public function getInvites()
    {
        $this->__load();
        return parent::getInvites();
    }

    public function getType()
    {
        $this->__load();
        return parent::getType();
    }

    public function getAvatarSrc()
    {
        $this->__load();
        return parent::getAvatarSrc();
    }

    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setTotalMembers($count)
    {
        $this->__load();
        return parent::setTotalMembers($count);
    }

    public function getUsername()
    {
        $this->__load();
        return parent::getUsername();
    }

    public function setUsername($username)
    {
        $this->__load();
        return parent::setUsername($username);
    }

    public function setPassword($password)
    {
        $this->__load();
        return parent::setPassword($password);
    }

    public function getPassword()
    {
        $this->__load();
        return parent::getPassword();
    }

    public function getSalt()
    {
        $this->__load();
        return parent::getSalt();
    }

    public function getRoles()
    {
        $this->__load();
        return parent::getRoles();
    }

    public function eraseCredentials()
    {
        $this->__load();
        return parent::eraseCredentials();
    }

    public function isEqualTo(\Symfony\Component\Security\Core\User\UserInterface $user)
    {
        $this->__load();
        return parent::isEqualTo($user);
    }

    public function serialize()
    {
        $this->__load();
        return parent::serialize();
    }

    public function unserialize($serialized)
    {
        $this->__load();
        return parent::unserialize($serialized);
    }

    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }

    public function setManagerFirstName($managerFirstName)
    {
        $this->__load();
        return parent::setManagerFirstName($managerFirstName);
    }

    public function getManagerFirstName()
    {
        $this->__load();
        return parent::getManagerFirstName();
    }

    public function setManagerLastName($managerLastName)
    {
        $this->__load();
        return parent::setManagerLastName($managerLastName);
    }

    public function getManagerLastName()
    {
        $this->__load();
        return parent::getManagerLastName();
    }

    public function setManagerEmail($managerEmail)
    {
        $this->__load();
        return parent::setManagerEmail($managerEmail);
    }

    public function getManagerEmail()
    {
        $this->__load();
        return parent::getManagerEmail();
    }

    public function setManagerPhone($managerPhone)
    {
        $this->__load();
        return parent::setManagerPhone($managerPhone);
    }

    public function getManagerPhone()
    {
        $this->__load();
        return parent::getManagerPhone();
    }

    public function setOfficialName($officialName)
    {
        $this->__load();
        return parent::setOfficialName($officialName);
    }

    public function getOfficialName()
    {
        $this->__load();
        return parent::getOfficialName();
    }

    public function setOfficialDescription($officialDescription)
    {
        $this->__load();
        return parent::setOfficialDescription($officialDescription);
    }

    public function getOfficialDescription()
    {
        $this->__load();
        return parent::getOfficialDescription();
    }

    public function setOfficialType($officialType)
    {
        $this->__load();
        return parent::setOfficialType($officialType);
    }

    public function getOfficialType()
    {
        $this->__load();
        return parent::getOfficialType();
    }

    public function setOfficialAddress($officialAddress)
    {
        $this->__load();
        return parent::setOfficialAddress($officialAddress);
    }

    public function getOfficialAddress()
    {
        $this->__load();
        return parent::getOfficialAddress();
    }

    public function setOfficialCity($officialCity)
    {
        $this->__load();
        return parent::setOfficialCity($officialCity);
    }

    public function getOfficialCity()
    {
        $this->__load();
        return parent::getOfficialCity();
    }

    public function setOfficialState($officialState)
    {
        $this->__load();
        return parent::setOfficialState($officialState);
    }

    public function getOfficialState()
    {
        $this->__load();
        return parent::getOfficialState();
    }

    public function setSalt($salt)
    {
        $this->__load();
        return parent::setSalt($salt);
    }

    public function setAvatar(\Symfony\Component\HttpFoundation\File\UploadedFile $avatar)
    {
        $this->__load();
        return parent::setAvatar($avatar);
    }

    public function getAvatar()
    {
        $this->__load();
        return parent::getAvatar();
    }

    public function getDefaultAvatar()
    {
        $this->__load();
        return parent::getDefaultAvatar();
    }

    public function setAvatarFileName($avatarFileName)
    {
        $this->__load();
        return parent::setAvatarFileName($avatarFileName);
    }

    public function getAvatarFileName()
    {
        $this->__load();
        return parent::getAvatarFileName();
    }

    public function setAvatarSource($avatarSource)
    {
        $this->__load();
        return parent::setAvatarSource($avatarSource);
    }

    public function getAvatarSource()
    {
        $this->__load();
        return parent::getAvatarSource();
    }

    public function setAvatarSourceFileName($avatarSourceFileName)
    {
        $this->__load();
        return parent::setAvatarSourceFileName($avatarSourceFileName);
    }

    public function getAvatarSourceFileName()
    {
        $this->__load();
        return parent::getAvatarSourceFileName();
    }

    public function setAvatarFilePath($avatarFilePath)
    {
        $this->__load();
        return parent::setAvatarFilePath($avatarFilePath);
    }

    public function getAvatarFilePath()
    {
        $this->__load();
        return parent::getAvatarFilePath();
    }

    public function getJoinStatus()
    {
        $this->__load();
        return parent::getJoinStatus();
    }

    public function getJoined(\Civix\CoreBundle\Entity\User $user)
    {
        $this->__load();
        return parent::getJoined($user);
    }

    public function getPicture()
    {
        $this->__load();
        return parent::getPicture();
    }

    public function setPicture($picture)
    {
        $this->__load();
        return parent::setPicture($picture);
    }

    public function addUser(\Civix\CoreBundle\Entity\UserGroup $user)
    {
        $this->__load();
        return parent::addUser($user);
    }

    public function removeUser(\Civix\CoreBundle\Entity\UserGroup $user)
    {
        $this->__load();
        return parent::removeUser($user);
    }

    public function getUsers()
    {
        $this->__load();
        return parent::getUsers();
    }

    public function getOwner()
    {
        $this->__load();
        return parent::getOwner();
    }

    public function setOwner(\Civix\CoreBundle\Entity\User $owner = NULL)
    {
        $this->__load();
        return parent::setOwner($owner);
    }

    public function setCreatedDate()
    {
        $this->__load();
        return parent::setCreatedDate();
    }

    public function setCreatedAt($createdAt)
    {
        $this->__load();
        return parent::setCreatedAt($createdAt);
    }

    public function getCreatedAt()
    {
        $this->__load();
        return parent::getCreatedAt();
    }

    public function getQuestionLimit()
    {
        $this->__load();
        return parent::getQuestionLimit();
    }

    public function setQuestionLimit($limit)
    {
        $this->__load();
        return parent::setQuestionLimit($limit);
    }

    public function getPetitionPercent()
    {
        $this->__load();
        return parent::getPetitionPercent();
    }

    public function setPetitionPercent($percent)
    {
        $this->__load();
        return parent::setPetitionPercent($percent);
    }

    public function getPetitionDuration()
    {
        $this->__load();
        return parent::getPetitionDuration();
    }

    public function setPetitionDuration($duration)
    {
        $this->__load();
        return parent::setPetitionDuration($duration);
    }

    public function getGroupType()
    {
        $this->__load();
        return parent::getGroupType();
    }

    public function setGroupType($type)
    {
        $this->__load();
        return parent::setGroupType($type);
    }

    public function setLocalState(\Civix\CoreBundle\Entity\State $localState = NULL)
    {
        $this->__load();
        return parent::setLocalState($localState);
    }

    public function getLocalState()
    {
        $this->__load();
        return parent::getLocalState();
    }

    public function getLocalDistrictId()
    {
        $this->__load();
        return parent::getLocalDistrictId();
    }

    public function addLocalRepresentative(\Civix\CoreBundle\Entity\Representative $localRepresentative)
    {
        $this->__load();
        return parent::addLocalRepresentative($localRepresentative);
    }

    public function removeLocalRepresentative(\Civix\CoreBundle\Entity\Representative $localRepresentative)
    {
        $this->__load();
        return parent::removeLocalRepresentative($localRepresentative);
    }

    public function getLocalRepresentatives()
    {
        $this->__load();
        return parent::getLocalRepresentatives();
    }

    public function setLocalDistrict(\Civix\CoreBundle\Entity\District $localDistrict = NULL)
    {
        $this->__load();
        return parent::setLocalDistrict($localDistrict);
    }

    public function getLocalDistrict()
    {
        $this->__load();
        return parent::getLocalDistrict();
    }

    public function setMembershipControl($membershipControl)
    {
        $this->__load();
        return parent::setMembershipControl($membershipControl);
    }

    public function getMembershipControl()
    {
        $this->__load();
        return parent::getMembershipControl();
    }

    public function setMembershipPasscode($membershipPasscode)
    {
        $this->__load();
        return parent::setMembershipPasscode($membershipPasscode);
    }

    public function getMembershipPasscode()
    {
        $this->__load();
        return parent::getMembershipPasscode();
    }

    public function addField(\Civix\CoreBundle\Entity\Group\GroupField $fields)
    {
        $this->__load();
        return parent::addField($fields);
    }

    public function removeField(\Civix\CoreBundle\Entity\Group\GroupField $fields)
    {
        $this->__load();
        return parent::removeField($fields);
    }

    public function getFields()
    {
        $this->__load();
        return parent::getFields();
    }

    public function setFillFieldsRequired($fillFieldsRequired)
    {
        $this->__load();
        return parent::setFillFieldsRequired($fillFieldsRequired);
    }

    public function getFillFieldsRequired()
    {
        $this->__load();
        return parent::getFillFieldsRequired();
    }

    public function updateFillFieldsRequired()
    {
        $this->__load();
        return parent::updateFillFieldsRequired();
    }

    public function getFieldsIds()
    {
        $this->__load();
        return parent::getFieldsIds();
    }

    public function setPetitionPerMonth($petitionPerMonth)
    {
        $this->__load();
        return parent::setPetitionPerMonth($petitionPerMonth);
    }

    public function getPetitionPerMonth()
    {
        $this->__load();
        return parent::getPetitionPerMonth();
    }

    public function setAcronym($acronym)
    {
        $this->__load();
        return parent::setAcronym($acronym);
    }

    public function getAcronym()
    {
        $this->__load();
        return parent::getAcronym();
    }

    public function getDefaultAcronym()
    {
        $this->__load();
        return parent::getDefaultAcronym();
    }

    public function getAddressArray()
    {
        $this->__load();
        return parent::getAddressArray();
    }

    public function isCommercial()
    {
        $this->__load();
        return parent::isCommercial();
    }

    public function getEmail()
    {
        $this->__load();
        return parent::getEmail();
    }

    public function getRequiredPermissions()
    {
        $this->__load();
        return parent::getRequiredPermissions();
    }

    public function serializeRequiredPermissions()
    {
        $this->__load();
        return parent::serializeRequiredPermissions();
    }

    public function setRequiredPermissions($permissions)
    {
        $this->__load();
        return parent::setRequiredPermissions($permissions);
    }

    public function hasRequiredPermissions($key)
    {
        $this->__load();
        return parent::hasRequiredPermissions($key);
    }

    public function setPermissionsChangedAt($date)
    {
        $this->__load();
        return parent::setPermissionsChangedAt($date);
    }

    public function getPermissionsChangedAt()
    {
        $this->__load();
        return parent::getPermissionsChangedAt();
    }

    public function getGroupSections()
    {
        $this->__load();
        return parent::getGroupSections();
    }

    public function setGroupSections($groupSection)
    {
        $this->__load();
        return parent::setGroupSections($groupSection);
    }

    public function getLocationName()
    {
        $this->__load();
        return parent::getLocationName();
    }

    public function setLocationName($locationName)
    {
        $this->__load();
        return parent::setLocationName($locationName);
    }

    public function getChildren()
    {
        $this->__load();
        return parent::getChildren();
    }

    public function setChildren($children)
    {
        $this->__load();
        return parent::setChildren($children);
    }

    public function getParent()
    {
        $this->__load();
        return parent::getParent();
    }

    public function setParent($parent)
    {
        $this->__load();
        return parent::setParent($parent);
    }

    public function isLocalGroup()
    {
        $this->__load();
        return parent::isLocalGroup();
    }

    public function isCountryGroup()
    {
        $this->__load();
        return parent::isCountryGroup();
    }

    public function isStateGroup()
    {
        $this->__load();
        return parent::isStateGroup();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'groupType', 'username', 'password', 'salt', 'avatarFileName', 'avatarSourceFileName', 'managerFirstName', 'managerLastName', 'managerEmail', 'managerPhone', 'officialName', 'officialDescription', 'acronym', 'officialType', 'officialAddress', 'officialCity', 'officialState', 'createdAt', 'questionLimit', 'petitionPercent', 'petitionDuration', 'membershipControl', 'membershipPasscode', 'fillFieldsRequired', 'petitionPerMonth', 'requiredPermissions', 'permissionsChangedAt', 'locationName', 'users', 'invites', 'owner', 'localState', 'localDistrict', 'localRepresentatives', 'fields', 'groupSections', 'parent', 'children');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}