<?php

namespace Proxies\__CG__\Civix\CoreBundle\Entity\Micropetitions;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Answer extends \Civix\CoreBundle\Entity\Micropetitions\Answer implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setOptionId($optionId)
    {
        $this->__load();
        return parent::setOptionId($optionId);
    }

    public function getOptionId()
    {
        $this->__load();
        return parent::getOptionId();
    }

    public function setUser(\Civix\CoreBundle\Entity\User $user = NULL)
    {
        $this->__load();
        return parent::setUser($user);
    }

    public function getUser()
    {
        $this->__load();
        return parent::getUser();
    }

    public function setPetition(\Civix\CoreBundle\Entity\Micropetitions\Petition $petition = NULL)
    {
        $this->__load();
        return parent::setPetition($petition);
    }

    public function getPetition()
    {
        $this->__load();
        return parent::getPetition();
    }

    public function setCreatedAt($createdAt)
    {
        $this->__load();
        return parent::setCreatedAt($createdAt);
    }

    public function getCreatedAt()
    {
        $this->__load();
        return parent::getCreatedAt();
    }

    public function setCreationData()
    {
        $this->__load();
        return parent::setCreationData();
    }

    public function setPetitionId($petitionId)
    {
        $this->__load();
        return parent::setPetitionId($petitionId);
    }

    public function getPetitionId()
    {
        $this->__load();
        return parent::getPetitionId();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'optionId', 'petitionId', 'createdAt', 'user', 'petition');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}