<?php

namespace Proxies\__CG__\Civix\CoreBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Representative extends \Civix\CoreBundle\Entity\Representative implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getType()
    {
        $this->__load();
        return parent::getType();
    }

    public function getAvatarSrc()
    {
        $this->__load();
        return parent::getAvatarSrc();
    }

    public function serialize()
    {
        $this->__load();
        return parent::serialize();
    }

    public function unserialize($serialized)
    {
        $this->__load();
        return parent::unserialize($serialized);
    }

    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function getFirstName()
    {
        $this->__load();
        return parent::getFirstName();
    }

    public function getFax()
    {
        $this->__load();
        return parent::getFax();
    }

    public function setFax($fax)
    {
        $this->__load();
        return parent::setFax($fax);
    }

    public function getWebsite()
    {
        $this->__load();
        return parent::getWebsite();
    }

    public function setWebsite($website)
    {
        $this->__load();
        return parent::setWebsite($website);
    }

    public function setFirstName($name)
    {
        $this->__load();
        return parent::setFirstName($name);
    }

    public function getLastName()
    {
        $this->__load();
        return parent::getLastName();
    }

    public function setLastName($name)
    {
        $this->__load();
        return parent::setLastName($name);
    }

    public function getUsername()
    {
        $this->__load();
        return parent::getUsername();
    }

    public function setUsername($username)
    {
        $this->__load();
        return parent::setUsername($username);
    }

    public function setPassword($password)
    {
        $this->__load();
        return parent::setPassword($password);
    }

    public function getPassword()
    {
        $this->__load();
        return parent::getPassword();
    }

    public function getSalt()
    {
        $this->__load();
        return parent::getSalt();
    }

    public function getRoles()
    {
        $this->__load();
        return parent::getRoles();
    }

    public function getOfficialTitle()
    {
        $this->__load();
        return parent::getOfficialTitle();
    }

    public function getOfficialName()
    {
        $this->__load();
        return parent::getOfficialName();
    }

    public function setOfficialTitle($officialTitle)
    {
        $this->__load();
        return parent::setOfficialTitle($officialTitle);
    }

    public function setCountry($country)
    {
        $this->__load();
        return parent::setCountry($country);
    }

    public function getCountry()
    {
        $this->__load();
        return parent::getCountry();
    }

    public function setState($state)
    {
        $this->__load();
        return parent::setState($state);
    }

    public function getState()
    {
        $this->__load();
        return parent::getState();
    }

    public function getOfficialState()
    {
        $this->__load();
        return parent::getOfficialState();
    }

    public function getStateCode()
    {
        $this->__load();
        return parent::getStateCode();
    }

    public function setCity($city)
    {
        $this->__load();
        return parent::setCity($city);
    }

    public function getCity()
    {
        $this->__load();
        return parent::getCity();
    }

    public function getOfficialCity()
    {
        $this->__load();
        return parent::getOfficialCity();
    }

    public function setOfficialAddress($officialAddress)
    {
        $this->__load();
        return parent::setOfficialAddress($officialAddress);
    }

    public function getOfficialAddress()
    {
        $this->__load();
        return parent::getOfficialAddress();
    }

    public function setOfficialPhone($officialPhone)
    {
        $this->__load();
        return parent::setOfficialPhone($officialPhone);
    }

    public function getOfficialPhone()
    {
        $this->__load();
        return parent::getOfficialPhone();
    }

    public function setStatus($status)
    {
        $this->__load();
        return parent::setStatus($status);
    }

    public function getStatus()
    {
        $this->__load();
        return parent::getStatus();
    }

    public function getEmail()
    {
        $this->__load();
        return parent::getEmail();
    }

    public function setEmail($email)
    {
        $this->__load();
        return parent::setEmail($email);
    }

    public function eraseCredentials()
    {
        $this->__load();
        return parent::eraseCredentials();
    }

    public function equals(\Civix\CoreBundle\Entity\UserInterface $user)
    {
        $this->__load();
        return parent::equals($user);
    }

    public function setSalt($salt)
    {
        $this->__load();
        return parent::setSalt($salt);
    }

    public function setAvatar(\Symfony\Component\HttpFoundation\File\UploadedFile $avatar)
    {
        $this->__load();
        return parent::setAvatar($avatar);
    }

    public function getAvatar()
    {
        $this->__load();
        return parent::getAvatar();
    }

    public function getDefaultAvatar()
    {
        $this->__load();
        return parent::getDefaultAvatar();
    }

    public function setAvatarFileName($avatarFileName)
    {
        $this->__load();
        return parent::setAvatarFileName($avatarFileName);
    }

    public function getAvatarFileName()
    {
        $this->__load();
        return parent::getAvatarFileName();
    }

    public function setAvatarSourceFileName($avatarSourceFileName)
    {
        $this->__load();
        return parent::setAvatarSourceFileName($avatarSourceFileName);
    }

    public function getAvatarSourceFileName()
    {
        $this->__load();
        return parent::getAvatarSourceFileName();
    }

    public function setAvatarSource($avatarSource)
    {
        $this->__load();
        return parent::setAvatarSource($avatarSource);
    }

    public function getAvatarSource()
    {
        $this->__load();
        return parent::getAvatarSource();
    }

    public function getDistrictId()
    {
        $this->__load();
        return parent::getDistrictId();
    }

    public function getStorageId()
    {
        $this->__load();
        return parent::getStorageId();
    }

    public function setStorageId($storageId)
    {
        $this->__load();
        return parent::setStorageId($storageId);
    }

    public function setAvatarFilePath($avatarFilePath)
    {
        $this->__load();
        return parent::setAvatarFilePath($avatarFilePath);
    }

    public function getAvatarFilePath()
    {
        $this->__load();
        return parent::getAvatarFilePath();
    }

    public function setStorageUpdateAt($updateDate)
    {
        $this->__load();
        return parent::setStorageUpdateAt($updateDate);
    }

    public function getStorageUpdateAt()
    {
        $this->__load();
        return parent::getStorageUpdateAt();
    }

    public function getQuestionLimit()
    {
        $this->__load();
        return parent::getQuestionLimit();
    }

    public function setQuestionLimit($limit)
    {
        $this->__load();
        return parent::setQuestionLimit($limit);
    }

    public function getIsNonLegislative()
    {
        $this->__load();
        return parent::getIsNonLegislative();
    }

    public function setIsNonLegislative($isNonLegislative)
    {
        $this->__load();
        return parent::setIsNonLegislative($isNonLegislative);
    }

    public function getRepresentativeStorage()
    {
        $this->__load();
        return parent::getRepresentativeStorage();
    }

    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }

    public function isLocalLeader()
    {
        $this->__load();
        return parent::isLocalLeader();
    }

    public function setRepresentativeStorage(\Civix\CoreBundle\Entity\RepresentativeStorage $representativeStorage = NULL)
    {
        $this->__load();
        return parent::setRepresentativeStorage($representativeStorage);
    }

    public function setLocalGroup(\Civix\CoreBundle\Entity\Group $localGroup = NULL)
    {
        $this->__load();
        return parent::setLocalGroup($localGroup);
    }

    public function getLocalGroup()
    {
        $this->__load();
        return parent::getLocalGroup();
    }

    public function isLocalAdmin()
    {
        $this->__load();
        return parent::isLocalAdmin();
    }

    public function setDistrict(\Civix\CoreBundle\Entity\District $district = NULL)
    {
        $this->__load();
        return parent::setDistrict($district);
    }

    public function getDistrict()
    {
        $this->__load();
        return parent::getDistrict();
    }

    public function getBirthday()
    {
        $this->__load();
        return parent::getBirthday();
    }

    public function getStartTerm()
    {
        $this->__load();
        return parent::getStartTerm();
    }

    public function getEndTerm()
    {
        $this->__load();
        return parent::getEndTerm();
    }

    public function getFacebook()
    {
        $this->__load();
        return parent::getFacebook();
    }

    public function getTwitter()
    {
        $this->__load();
        return parent::getTwitter();
    }

    public function getYoutube()
    {
        $this->__load();
        return parent::getYoutube();
    }

    public function getAddressArray()
    {
        $this->__load();
        return parent::getAddressArray();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'firstName', 'lastName', 'username', 'password', 'salt', 'avatarFileName', 'avatarSourceFileName', 'officialTitle', 'country', 'city', 'officialAddress', 'officialPhone', 'status', 'email', 'fax', 'website', 'storageId', 'storageUpdateAt', 'questionLimit', 'isNonLegislative', 'state', 'district', 'representativeStorage', 'localGroup');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}