<?php

namespace Proxies\__CG__\Civix\CoreBundle\Entity\Stripe;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class AccountRepresentative extends \Civix\CoreBundle\Entity\Stripe\AccountRepresentative implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getUser()
    {
        $this->__load();
        return parent::getUser();
    }

    public function setUser(\Civix\CoreBundle\Entity\Representative $user = NULL)
    {
        $this->__load();
        return parent::setUser($user);
    }

    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setId($id)
    {
        $this->__load();
        return parent::setId($id);
    }

    public function getStripeId()
    {
        $this->__load();
        return parent::getStripeId();
    }

    public function setStripeId($stripeId)
    {
        $this->__load();
        return parent::setStripeId($stripeId);
    }

    public function getSecretKey()
    {
        $this->__load();
        return parent::getSecretKey();
    }

    public function setSecretKey($secretKey)
    {
        $this->__load();
        return parent::setSecretKey($secretKey);
    }

    public function getPublishableKey()
    {
        $this->__load();
        return parent::getPublishableKey();
    }

    public function setPublishableKey($publishableKey)
    {
        $this->__load();
        return parent::setPublishableKey($publishableKey);
    }

    public function getBankAccounts()
    {
        $this->__load();
        return parent::getBankAccounts();
    }

    public function updateBankAccounts($bankAccounts)
    {
        $this->__load();
        return parent::updateBankAccounts($bankAccounts);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'stripeId', 'secretKey', 'publishableKey', 'bankAccounts', 'user');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}